# .travis.yml
language: php
php:
  - 5.6
  - 7.0

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && php vendor/bin/coveralls -vbuild/logs/clover.xml